fix(href): add href to a tags so hyperlinks appear correctly
ngageoint/opensphere pull request #1169
Opened 2021-02-10 20:23 UTC by lilysikes

After JQuery update it was discovered that <a> tags without href don't appear correctly. This ticket fixes those issues, but for now we must change "attribute-allowed-values" errors to be warnings.

2021-02-11 16:25 UTC, csgibson approved these changes

2021-02-11 16:31 UTC, csgibson commented
@wallw-bits this is in line with what we are doing elsewhere but maybe not necessary for opensphere. Yay or Nay?

2021-02-11 17:28 UTC, wallw-bits commented
I am not a fan of using an anchor tag just for `ng-click`. Since these do not link anywhere, they should not be anchors in the first place. They were probably done that way because someone copy/pasted from the bootstrap examples, which intend for the `href` to have a value.

2021-02-11 20:54 UTC, csgibson commented
@wallw-bits I agree with that. I think it was the result of some of the bootstrap defaults like you mentioned. Anchor tags pull in things like 'cursor: pointer' automatically. There might be other considerations I am not aware of. Not sure if @jsalankey remembers?

We don't have to accept this PR though if it's not what we want to do. I think @schmidtk got these working after the jquery upgrade already.

2021-02-12 13:08 UTC, schmidtk commented
Bootstrap's examples use `<a href="#" ...>` for navs, which is what I used in [this commit](https://github.com/ngageoint/opensphere/commit/55dce78a0f53beb515089f1ed2950c331f1bb1e3) to fix the layers window tabs.

In doing some reading, it seems both `href="#"` and an empty `href` point to the top of the current document and should have the same behavior. I tested in Chrome, Firefox, and Edge, and both approaches had the intended behavior without unwanted side effects.

I'm fine either either approach but we should pick one and stick with it for consistency. Given the empty `href` is shorter and doesn't imply a document fragment, that might be better than Bootstrap's `href="#"`.

2021-02-12 13:12 UTC, schmidtk commented
Sorry, I take that back. Given this PR introduces lint errors which are worked around by changing `attribute-allowed-values` to a warning, we should use Bootstrap's recommended `href="#"` pattern instead.

2021-02-12 17:42 UTC, wallw-bits commented
I don't think `href="#"` will play nice with Angular. A good portion of those styles are not specific to the tag, and therefore we should try making those divs or something first.

2021-02-12 18:37 UTC, schmidtk commented
If `cursor: pointer` is the only thing we lose by switching to a div, maybe we should just add that to `.nav-link` in the Bootstrap overrides. I agree with Will, that would be preferable to using anchors on elements that aren't actually links.

2021-03-03 16:25 UTC, schmidtk requested changes

2021-03-03 16:25 UTC, schmidtk commented on .htmlvalidate.json
> +    "attribute-allowed-values": "warn",
We should avoid downgrading existing errors to warnings, and instead find a solution that does not produce errors.

2021-03-03 16:25 UTC, schmidtk commented on views/filter/editfilters.html
> +        <li class="nav-item"><a href class="nav-link" ng-class="{active: tab == 'basic'}" ng-click="filters.setTab('basic')">Basic</a></li>
It sounds like the only thing preventing us from using `div` here is the lack of `cursor: pointer`. Is that accurate? If so, I wouldn't be opposed to adding that to `.nav-link` in our Bootstrap overrides. I agree with @wallw-bits on not using anchor tags for things that aren't links.

2021-03-17 13:49 UTC, closed without merging