fix: polyfill chardetng-wasm with jschardet
ngageoint/opensphere pull request #1239
Opened 2021-04-12 16:25 UTC by wallw-bits

This fixes file import in environments without Web Assembly.

2021-04-12 19:10 UTC, csgibson approved these changes

2021-04-13 12:22 UTC, schmidtk requested changes

2021-04-13 12:22 UTC, schmidtk commented on src/polyfill/chardetng.js
> +const JSCHARDET_BASE_PATH = goog.define('JSCHARDET_BASE_PATH', 'vendor/jschardet');
This covers the compiled build, but we'll want to add it to `moduleDefines` in `package.json` for the dev build.

2021-04-13 16:37 UTC, schmidtk approved these changes

2021-04-15 17:09 UTC, merged