feat: test ellipse configuration columns for config-based suggestions
ngageoint/opensphere pull request #1332
Opened 2021-07-16 19:21 UTC by jkae

- feat: "Suggested Columns" optgroup for ellipse column selections (csv import, etc.)
- feat: created a directive to help with suggested columns / other situations that call for dynamic optgroups from separate lists
- fix: resolve logic / naming issues in ellipse column directive
- refactor: goog.module conversions for some import mapping types

2021-07-16 20:07 UTC, arwatts16 commented
Are there related MRs for the highside configs to move `allowEllipseConfiguration`?

2021-07-19 21:51 UTC, bcleveland1022 submitted a review, later dismissed

2021-07-20 16:02 UTC, schmidtk requested changes

2021-07-20 16:56 UTC, schmidtk approved these changes

2021-07-20 17:15 UTC, merged