light-server -> http-server
ngageoint/opensphere pull request #1452
Opened 2024-06-26 19:43 UTC by sethahrenbach

+ remediates dependency problems associated with `light-server` by using `http-server`

2024-06-26 20:52 UTC, JoshNels requested changes
`yarn stop-server` is still using light-server

2024-06-26 20:52 UTC, JoshNels commented on package.json
>      "stop-server:darwin:linux": "pkill -f light-server",
`yarn stop server` should be adjusted to use http-server as well

2024-07-12 16:22 UTC, cwerthomni approved these changes

2024-07-12 16:23 UTC, cwerthomni approved these changes

2024-07-12 16:24 UTC, cwerthomni approved these changes

2024-07-12 16:24 UTC, merged